#[allow(dead_code)] // TODO(xymostech): remove this once all of these are used
#[derive(Debug, PartialEq)]
pub enum DVICommand {
    SetCharN(u8),
    Set1(u8),
    Set2(u16),
    Set3(u32),
    Set4(i32),
    SetRule {
        height: i32,
        width: i32,
    },
    Put1(u8),
    Put2(u16),
    Put3(u32),
    Put4(i32),
    PutRule {
        height: i32,
        width: i32,
    },
    Nop,
    Bop {
        cs: [i32; 10],
        pointer: i32,
    },
    Eop,
    Push,
    Pop,
    Right1(i8),
    Right2(i16),
    Right3(i32),
    Right4(i32),
    W0,
    W1(i8),
    W2(i16),
    W3(i32),
    W4(i32),
    X0,
    X1(i8),
    X2(i16),
    X3(i32),
    X4(i32),
    Down1(i8),
    Down2(i16),
    Down3(i32),
    Down4(i32),
    Y0,
    Y1(i8),
    Y2(i16),
    Y3(i32),
    Y4(i32),
    Z0,
    Z1(i8),
    Z2(i16),
    Z3(i32),
    Z4(i32),
    FntNumN(u8),
    Fnt1(u8),
    Fnt2(u16),
    Fnt3(u32),
    Fnt4(i32),
    XXX1(Vec<u8>),
    XXX2(Vec<u8>),
    XXX3(Vec<u8>),
    XXX4(Vec<u8>),
    FntDef1 {
        font_num: u8,
        checksum: u32,
        scale: u32,
        design_size: u32,
        area: u8,
        length: u8,
        font_name: String,
    },
    FntDef2 {
        font_num: u16,
        checksum: u32,
        scale: u32,
        design_size: u32,
        area: u8,
        length: u8,
        font_name: String,
    },
    FntDef3 {
        font_num: u32,
        checksum: u32,
        scale: u32,
        design_size: u32,
        area: u8,
        length: u8,
        font_name: String,
    },
    FntDef4 {
        font_num: u32,
        checksum: u32,
        scale: u32,
        design_size: u32,
        area: u8,
        length: u8,
        font_name: String,
    },
    Pre {
        format: u8,
        num: u32,
        den: u32,
        mag: u32,
        comment: Vec<u8>,
    },
    Post {
        pointer: u32,
        num: u32,
        den: u32,
        mag: u32,
        max_page_height: u32,
        max_page_width: u32,
        max_stack_depth: u16,
        num_pages: u16,
    },
    PostPost {
        post_pointer: u32,
        format: u8,
        tail: u8,
    },
}

/// A faithful representation of a DVI file, consisting of the DVI commands.
/// Does no interpretation of the contents of the file, so this could contain
/// invalid constructs.
#[derive(Debug, PartialEq)]
pub struct DVIFile {
    pub commands: Vec<DVICommand>,
}
